### ISSUE TITLE
Optimize memory consumption on using levels > 1

### ISSUE THREAD

**Issue by mhmdiaa** [trickest/mksub#4]
https://github.com/trickest/mksub/issues/2
> it would be good if there is some tweak to optimize memory consumption on -l 3 with a single domain and a list of approx 5k
Hogging memory on -l 2 with a single domain and list of 10k

We can try to write output directly to stdout to avoid allocating memory for the whole wordlist.

**Comment by PolovinaD** [comment]
Resolved! Enjoy it and feel free to send any feedback 🚀  @jaikishantulswani

**Comment by jaikishantulswani** [comment]
@PolovinaD Thank you but there is still an issue as I am not getting any output.

**Comment by PolovinaD** [comment]
@jaikishantulswani By default there is no printing to stdout because it slows everything down. It's saved into a folder named `mksub-out` instead (if you haven't used `-o` parameter to change it), and then into one or multiple files inside that folder. If you want to watch it on stdout just add `-silent=false`.

Also, if you're using the compiled binary, that's the old version. We're still testing `mksub` on [trickest.io](https://trickest.io), so I'll publish a new release as soon as we make sure it works well with other tools and the platform itself.

I hope this helps 😄
